name: my_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geocoding: ^3.0.0 
  shared_preferences: ^2.2.2
  provider: ^6.1.2  
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.5
  google_sign_in: ^6.3.0
  image_picker: ^0.8.7+4
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.6
  cached_network_image: ^3.3.1
  path: ^1.9.1
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/logo1.png"
  android: true
  ios: true
  macos:
    generate: true
  windows:
    generate: true
    icon_size: 48
  linux:
    generate: true
  web:
    generate: true

flutter:
  uses-material-design: true

  assets:
    - assets/logo_white.png
    - assets/Gala.png
    - assets/logo.png
    - assets/logo1.png
    - assets/user.png
    - assets/naga_city.png
    - assets/pili.jpg
    - assets/siruma.jpg
    - assets/caramoan.png
    - assets/pasacao.png
    - assets/tinambac.jpg
    - assets/bg_settings.png
    - assets/fare.png
    - assets/parks.png
    - assets/beach.png
    - assets/nearby.png
    - assets/inuman.png
    - assets/cafe.png
    - assets/directions.png
    - assets/restaurant.png
    - assets/login_background.png
    - assets/google_icon.png
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/bg2.png
    - assets/onboarding3.png
    - assets/blueloc.png
    - assets/allow_loc.png
    - assets/success.png
    - assets/images/lemon.png
    - assets/images/coffee.png
    - assets/images/menu1.png
    - assets/images/clatte.png
    - assets/icons/location.png
    - assets/icons/tricycle.png
    - assets/icons/settings.png
    - assets/icons/menu.png
    - assets/icons/star_filled.png
    - assets/images/tea_bag.png
    - assets/images/chocolate.png
    - assets/images/location.png
    - assets/images/matcha.png
    - assets/images/mlatte.png
    - assets/images/mclatte.png
    - assets/images/slatte.png
    - assets/images/mglatte.png
    - assets/images/mslatte.png
    - assets/images/mm.png
    - assets/images/blatte.png
    - assets/images/mb.png
    - assets/aws_map.html

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
    - family: Sarina
      fonts:
        - asset: assets/fonts/Sarina-Regular.ttf